import type {
  Listing,
  ListingProvider,
  RateProvider,
  RentProvider,
} from "./types";

/** SAMPLE DATA ONLY. Addresses are fictional. Replace with Constellation / HouseCanary / BankingBridge. */
const SAMPLE: (Listing & { rent: number })[] = [
  {
    id: "ca-1",
    address: "1204 Alder St",
    city: "Fresno",
    state: "CA",
    zip: "93706",
    price: 349000,
    beds: 3,
    baths: 2,
    sqft: 1420,
    propertyType: "SFR",
    daysOnMarket: 12,
    photoUrl: "/images/garden-home.jpg",
    source: "fixture",
    rent: 2450,
  },
  {
    id: "ca-2",
    address: "88 Marina Way #4",
    city: "Sacramento",
    state: "CA",
    zip: "95815",
    price: 425000,
    beds: 3,
    baths: 2.5,
    sqft: 1610,
    propertyType: "Townhome",
    daysOnMarket: 31,
    photoUrl: "/images/courtyard-home.jpg",
    source: "fixture",
    rent: 2650,
  },
  {
    id: "ca-3",
    address: "3310 Ocean Bluff Dr",
    city: "San Diego",
    state: "CA",
    zip: "92109",
    price: 985000,
    beds: 4,
    baths: 3,
    sqft: 2050,
    propertyType: "SFR",
    daysOnMarket: 9,
    photoUrl: "/images/pool-home.jpg",
    source: "fixture",
    rent: 4900,
  },
  {
    id: "ca-4",
    address: "705 Kern Ave",
    city: "Bakersfield",
    state: "CA",
    zip: "93307",
    price: 289000,
    beds: 3,
    baths: 1.5,
    sqft: 1180,
    propertyType: "SFR",
    daysOnMarket: 44,
    photoUrl: "/images/modern-home.jpg",
    source: "fixture",
    rent: 2200,
  },
  {
    id: "ca-5",
    address: "52 Orchard Ln",
    city: "Stockton",
    state: "CA",
    zip: "95207",
    price: 379000,
    beds: 4,
    baths: 2,
    sqft: 1760,
    propertyType: "SFR",
    daysOnMarket: 18,
    photoUrl: "/images/classic-home.jpg",
    source: "fixture",
    rent: 2600,
  },
  {
    id: "tx-1",
    address: "9021 Bluebonnet Ct",
    city: "Houston",
    state: "TX",
    zip: "77036",
    price: 245000,
    beds: 3,
    baths: 2,
    sqft: 1500,
    propertyType: "SFR",
    daysOnMarket: 22,
    photoUrl: "/images/garden-home.jpg",
    source: "fixture",
    rent: 1950,
  },
  {
    id: "tx-2",
    address: "410 Mesquite Rd",
    city: "San Antonio",
    state: "TX",
    zip: "78221",
    price: 210000,
    beds: 3,
    baths: 2,
    sqft: 1320,
    propertyType: "SFR",
    daysOnMarket: 40,
    photoUrl: "/images/classic-home.jpg",
    source: "fixture",
    rent: 1800,
  },
  {
    id: "tx-3",
    address: "1600 Lakeview Blvd",
    city: "Dallas",
    state: "TX",
    zip: "75216",
    price: 315000,
    beds: 4,
    baths: 2.5,
    sqft: 1900,
    propertyType: "SFR",
    daysOnMarket: 6,
    photoUrl: "/images/courtyard-home.jpg",
    source: "fixture",
    rent: 2350,
  },
  {
    id: "tx-4",
    address: "77 Live Oak Pl",
    city: "Austin",
    state: "TX",
    zip: "78744",
    price: 455000,
    beds: 3,
    baths: 2,
    sqft: 1700,
    propertyType: "SFR",
    daysOnMarket: 27,
    photoUrl: "/images/modern-home.jpg",
    source: "fixture",
    rent: 2750,
  },
  {
    id: "fl-1",
    address: "2418 Palmetto Dr",
    city: "Orlando",
    state: "FL",
    zip: "32808",
    price: 335000,
    beds: 3,
    baths: 2,
    sqft: 1450,
    propertyType: "SFR",
    daysOnMarket: 15,
    photoUrl: "/images/pool-home.jpg",
    source: "fixture",
    rent: 2500,
  },
  {
    id: "fl-2",
    address: "515 Gulfview Ave",
    city: "Tampa",
    state: "FL",
    zip: "33607",
    price: 399000,
    beds: 3,
    baths: 2,
    sqft: 1580,
    propertyType: "SFR",
    daysOnMarket: 33,
    photoUrl: "/images/garden-home.jpg",
    source: "fixture",
    rent: 2700,
  },
  {
    id: "fl-3",
    address: "12 Coral Reef Cir",
    city: "Miami",
    state: "FL",
    zip: "33142",
    price: 520000,
    beds: 3,
    baths: 2,
    sqft: 1350,
    propertyType: "SFR",
    daysOnMarket: 20,
    photoUrl: "/images/courtyard-home.jpg",
    source: "fixture",
    rent: 3100,
  },
  {
    id: "fl-4",
    address: "3308 Cypress Ln",
    city: "Jacksonville",
    state: "FL",
    zip: "32210",
    price: 268000,
    beds: 3,
    baths: 2,
    sqft: 1380,
    propertyType: "SFR",
    daysOnMarket: 51,
    photoUrl: "/images/classic-home.jpg",
    source: "fixture",
    rent: 2100,
  },
];

const rentById = new Map(SAMPLE.map((s) => [s.id, s.rent]));

export const fixtureListings: ListingProvider = {
  async search(q) {
    return SAMPLE.filter(
      (s) =>
        q.states.includes(s.state) &&
        (!q.zip || s.zip.startsWith(q.zip)) &&
        (q.minPrice === undefined || s.price >= q.minPrice) &&
        (q.maxPrice === undefined || s.price <= q.maxPrice),
    ).map(({ rent: _rent, ...listing }) => {
      void _rent;
      return listing;
    });
  },
};

export const fixtureRent: RentProvider = {
  async estimate(l) {
    const rent = rentById.get(l.id) ?? Math.round(l.price * 0.007);
    return {
      monthlyRent: rent,
      low: Math.round(rent * 0.92),
      high: Math.round(rent * 1.08),
      source: "fixture",
    };
  },
};

export const fixtureRate: RateProvider = {
  async quote() {
    return { rate: 0.0799, asOf: "Example assumption", source: "fixture" };
  },
};
